# Generated by Django 3.2.6 on 2021-09-17 17:36

import apps.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data', apps.app.models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
